[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
  # Use skipPatterns to ignore the Google Fonts SSL errors
  skipPatterns = [
    "fonts.gstatic.com",
    "fonts.googleapis.com"
    ]

[[plugins]]
  package = "netlify-plugin-subfont"

[[plugins]]
  package = "@netlify/plugin-lighthouse"